RETROSPECT_CREATE_MESSAGE = '회고 생성에 성공하셨습니다.'
RETROSPECT_NOT_FOUND_ROUTINE_DAYS = '존재하지 않는 루틴 또는 루틴 하는 날입니다.'
RETROSPECT_ALREADY_EXISTS = '회고가 이미 존재합니다.'
RETROSPECT_NOT_FOUND_ID = '해당 회고는 존재하지 않습니다.'
RETROSPECT_DETAIL_MESSAGE = '디테일 회고를 가져왔습니다.'
RETROSPECT_UPDATE_MESSAGE = '디테일 회고 수정 완료했습니다.'
RETROSPECT_DELETE_MESSAGE = '디테일 회고 삭제 완료했습니다.'
RETROSPECT_LIST_MESSAGE = '회고 리스트 가져오기 완료했습니다.'
