version: '3.3'

services:
  postgres.db:
    container_name: minning-postgres
    image: vixx170627/postgres-ko
    restart: unless-stopped
    ports:
      - "54320:5432"
    env_file:
      - .env
    volumes:
      - minning_volume:/var/lib/postgresql/data
volumes:
  minning_volume: